### PR TITLE
Updated dependencies to latest mlkit face/barcode to 0.7, and others

### PR DESCRIPTION
**Pull request by iBog**
Updated dependencies to latest packages:
  path_provider: ^2.0.15
  better_open_file: ^3.6.4
  google_mlkit_face_detection: ^0.7.0
  google_mlkit_barcode_scanning: ^0.7.0
  google_mlkit_text_recognition: ^0.8.1
  image: ^4.0.17
  meta: ^1.9.1
  video_player: ^2.6.1

## Description

Updated dependencies respecting to all breaking changes in ML libs, which become incompatible with ver 0.5.x

## Checklist

Before creating any Pull Request, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).

- [x] 📕 I read the [Contributing page](https://github.com/Apparence-io/camera_awesome/blob/master/CONTRIBUTING.md).
- [x] 🤝 I match the actual coding style.
- [x] ✅ I ran ```flutter analyze``` without any issues.

## Breaking Change

- [ ] 🛠 My feature contain breaking change.

*If your feature break something, please detail it*

### CODE REVIEW

**Comment by vlazdra** [comment]
Resolves #355

**Comment by g-apparence** [comment]
Sorry for the late answer. (Summer time)
I'll try this next week to accept this merge

**Comment by iBog** [comment]
> Sorry for the late answer. (Summer time) I'll try this next week to accept this merge

My update also outdated, latest ver of google_mlkit_face_detection for this moment is 0.8.0

**Comment by g-apparence** [comment]
I used you pull request and merged it with the new requirements of the mlkit plugin. 
Sorry to not have been able to look at it faster, I always really appreciate contributions !🙏🏻

**Pull request closed without merging**
