### PR TITLE
⬆️ Upgrade image dependency

### LINKED ISSUE #238: Outdated image package version dependency
## Steps to Reproduce

install latest camerawesome
try to install latest crop_your_image

## Expected results

no package version conflicts should be observed

## Actual results
```
Because crop_your_image >=0.7.4 depends on image ^4.0.6 and camerawesome 1.2.0 depends on image ^3.3.0, crop_your_image >=0.7.4 is incompatible with camerawesome 1.2.0.
And because no versions of camerawesome match >1.2.0 <2.0.0, crop_your_image >=0.7.4 is incompatible with camerawesome ^1.2.0.
So, because giftmate depends on both camerawesome ^1.2.0 and crop_your_image ^0.7.4, version solving failed.
pub get failed
```
## About your device

| Brand   | Model       | OS        |
| ------- | ----------- | --------- |
| *Samsung* | *A53*  | *Android 13*  |

Please update the image package dependency so we can use other packages that depend on more recent version of it

### PR DESCRIPTION
**Pull request by apalala-dev**
## Description

Upgrade `image` dependency to resolve conflicts with other packages.

Fixes #238.

## Checklist

Before creating any Pull Request, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).

- [x] 📕 I read the [Contributing page](https://github.com/Apparence-io/camera_awesome/blob/master/CONTRIBUTING.md).
- [x] 🤝 I match the actual coding style.
- [x] ✅ I ran ```flutter analyze``` without any issues.

## Breaking Change

- [x] 🛠 My feature contain breaking change.

Packages that rely on image 3.x will have compatibility issues with CamerAwesome.
However, since we have compatibility issues because other packages already rely on image 4.x, it's worth the upgrade.

### CODE REVIEW

**Comment by apalala-dev** [comment]
Note: this PR can't be merged since it depends on a git dependency for photofilters.
Photofilters will have to be upgraded first.

**Review by dim-apparence — APPROVED** [review]

**Comment by talamaska** [comment]
Are you sure this is enough? 
I'm having all sort of issues when trying to override the dependencies with the ones you suggested and image package 4.0.x
```
camerawesome-1.2.1/lib/src/orchestrator/states/photo_camera_state.dart:153:44: Error: Too many positional arguments: 0 allowed, but 3 found.
image-4.0.13/lib/src/image/image.dart:198:3: Context: Found this candidate, but the arguments don't match.
camerawesome-1.2.1/lib/src/orchestrator/states/photo_camera_state.dart:159:56: Error: The argument type 'Image' can't be assigned to the parameter type 'String'.
camerawesome-1.2.1/lib/src/orchestrator/states/photo_camera_state.dart:159:67: Error: The argument type 'String' can't be assigned to the parameter type 'Image'.
```

**Comment by g-apparence** [comment]
Yes, my bad. 
I've discussed that with the team and we are using a package to create the filters. 
It's currently using version 3.x of images and the author is not answering to our PR. 
We are working to remove this dependency.

**Comment by talamaska** [comment]
FYI I think it is working. i haven't tested filters, but the rest is compiling and looks like working fine.

**Pull request merged**
