### PR TITLE
Update with carousel_slider:5.0.0

### PR DESCRIPTION
**Pull request by millerf**
## Description

Update from #502 with `carousel_slider:5.0.0`

## Checklist

Before creating any Pull Request, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).

- [x] 📕 I read the [Contributing page](https://github.com/Apparence-io/camera_awesome/blob/master/CONTRIBUTING.md).
- [x] 🤝 I match the actual coding style.
- [x] ✅ I ran ```flutter analyze``` without any issues.

## Breaking Change

- [x] 🛠 My feature contain breaking change.

*If your feature break something, please detail it*

### CODE REVIEW

**Comment by g-apparence** [comment]
Hi thank you for doing this. 
Really appreciate your help. 

I am testing this and reviewing the code.

**Comment by millerf** [comment]
Most of the work is from @tonistayhungrystayfoolish / @bytemaster in this PR. I just used carousel_slider 5.0.0 ;)

**Comment by g-apparence** [comment]
Version 2.1.0 published 
Thank you all for your help 🙏🏻

**Comment by GTechMicah** [comment]
Thank You @g-apparence! That's awesome!

**Pull request merged**
