### PR TITLE
inverted preview fix

### PR DESCRIPTION
**Pull request by ps9310**
## Description

@g-apparence I've used your pull request at https://github.com/Apparence-io/CamerAwesome/pull/432 as a foundation for this current PR. The modifications related to the inverted flag have been excluded, while retaining the feature to obtain PreviewSize directly from the underlying platform. These updates have been successfully tested and are functioning well on both smartphones and tablets across platforms.

Additionally, I have eliminated files that can be ignored in Android Studio.

## Checklist

Before creating any Pull Request, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).

- [x] 📕 I read the [Contributing page](https://github.com/Apparence-io/camera_awesome/blob/master/CONTRIBUTING.md).
- [x] 🤝 I match the actual coding style.
- [x] ✅ I ran ```flutter analyze``` without any issues.

### CODE REVIEW

**Comment by g-apparence** [comment]
Hi, thank you a lot for this (really appreciate every contributions)
Did you rebase from the main branch? (This PR was a bit old)

**Comment by ps9310** [comment]
> Hi, thank you a lot for this (really appreciate every contributions) Did you rebase from the main branch? (This PR was a bit old)

Yes, I've looked into it. It appears it's in sync with the master branch.
rebase

**Comment by g-apparence** [comment]
Great now I understand why I had some questions about this 
There is also another PR #432 trying to fix this. 

There are certainly great things in both PR but I doubt we should merge both. 

As I've seen you enabled rotation on iPad and that's certainly the key here.

```
<key>UISupportedInterfaceOrientations~ipad</key>
<array>
<string>UIInterfaceOrientationLandscapeLeft</string>
<string>UIInterfaceOrientationLandscapeRight</string>
<string>UIInterfaceOrientationPortrait</string>
<string>UIInterfaceOrientationPortraitUpsideDown</string>
</array>
```

**Comment by g-apparence** [comment]
Made some tests on phones too and works perfectly yes. 
I merge it and will send a release. 
Thank you for your contribution @ps9310

**Pull request merged**
