### PR TITLE
Fix Patrol tests

### LINKED ISSUE #267: Patrol tests are broken
## Steps to Reproduce

Try to run Patrol tests following #248 using either `run_patrol.sh` or `run_native_android_tests.sh`.
Note that we need to call `patrol test` instead of `patrol drive` now according to the [docs](https://patrol.leancode.co/native/setup#integrate-with-native-side).
E.g.:
`patrol test --target integration_test/bundled_test.dart`

## Expected results

Tests should run.

## Actual results

After installing the 2 apps (_com.example.camera_app.test_ and _com.example.camera_app_) needed by Patrol to run the integration tests, nothing seem to happen:

```
seb@MacBook-Pro example % patrol test --target integration_test/bundled_test.dart
No device specified, using the first one (adb-68720a8-tWBeN4._adb-tls-connect._tcp.)
Every test target will be run 1 time(s)
• Building apk with entrypoint bundled_test.dart...
✓ Completed building apk with entrypoint bundled_test.dart (7.3s)
• Executing tests of apk with entrypoint bundled_test.dart on device adb-68720a8-tWBeN4._adb-tls-connect._tcp....
        See the report at: file:///Users/seb/dev/workspace/camera_awesome/example/build/app/reports/androidTests/connected/index.html
✗ Failed to execute tests of apk with entrypoint bundled_test.dart on device adb-68720a8-tWBeN4._adb-tls-connect._tcp. (Gradle test execution failed with code 1) (357.3s)
Exception: Gradle test execution failed with code 1
See the logs above to learn what happened. Also consider running with --verbose. If the logs still aren't useful, then it's a bug - please report it.
 FAIL  bundled_test.dart on adb-68720a8-tWBeN4._adb-tls-connect._tcp.
```

The mentioned report showed:
`Test run failed to complete. No test results`

## About your device

| Brand   | Model       | OS        |
| ------- | ----------- | --------- |
| *Xiaomi* | *Mi 9T*  | *MIUI 12.1.4 with Android 11*  |

## Your flutter version

<details>
<summary>flutter --version</summary>

```
Flutter 3.7.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9944297138 (5 weeks ago) • 2023-02-08 15:46:04 -0800
Engine • revision 248290d6d5
Tools • Dart 2.19.2 • DevTools 2.20.1
```

</details>

### PR DESCRIPTION
**Pull request by bartekpacia**
## Description

This PR fixes #267

## Checklist

Before creating any Pull Request, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).

- [x] 📕 I read the [Contributing page](https://github.com/Apparence-io/camera_awesome/blob/master/CONTRIBUTING.md).
- [x] 🤝 I match the actual coding style.
- [x] ✅ I ran ```flutter analyze``` without any issues.

## Breaking Change

- [ ] 🛠 My feature contains breaking change.

### CODE REVIEW

**Comment by bartekpacia** [comment]
`photo_test.dart` and `video_test.dart` pass. `ui_test.dart` crashes with a mysterious "Instrumentation crashed" when run with `patrol test`, but works when run with `patrol develop`.

**Comment by istornz** [comment]
Thanks a lot @bartekpacia 👍 
Your help is greatly appreciated 🥇

**Comment by apalala-dev** [comment]
Since you mentioned that there was a problem with ui_test, I tried an other one.

The tests didn't run after running the following command: `patrol test --target integration_test/photo_test.dart --verbose`

After looking at the logcat, I've noticed this:

<details>
<summary>Logs</summary>

```
2023-03-27 10:27:25.878  9084-9112  THREAD_STATE            com.example.camera_app               E    Thread[Binder:9084_3,5,main]
                                
Thread[Profile Saver,5,system]

Thread[Instr: androidx.test.runner.AndroidJUnitRunner,5,main]
  dalvik.system.VMStack.getThreadStackTrace(Native Method)
  java.lang.Thread.getStackTrace(Thread.java:1736)
  java.lang.Thread.getAllStackTraces(Thread.java:1812)
  androidx.test.runner.MonitoringInstrumentation.getThreadState(MonitoringInstrumentation.java:748)
  androidx.test.runner.MonitoringInstrumentation.dumpThreadStateToOutputs(MonitoringInstrumentation.java:743)
  androidx.test.runner.MonitoringInstrumentation.startActivitySync(MonitoringInstrumentation.java:547)
  androidx.test.rule.ActivityTestRule.launchActivity(ActivityTestRule.java:376)
  pl.leancode.patrol.PatrolTestRule.launchActivity(PatrolTestRule.kt:28)
  dev.flutter.plugins.integration_test.FlutterTestRunner.run(FlutterTestRunner.java:61)
  org.junit.runners.Suite.runChild(Suite.java:128)
  org.junit.runners.Suite.runChild(Suite.java:27)
  org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
  org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
  org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
  org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
  org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
  org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
  org.junit.runners.ParentRunner.run(ParentRunner.java:413)
  org.junit.runner.JUnitCore.run(JUnitCore.java:137)
  org.junit.runner.JUnitCore.run(JUnitCore.java:115)
  androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:67)
  androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:58)
  androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:446)
  android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2213)

Thread[FinalizerWatchdogDaemon,5,system]
  java.lang.Thread.sleep(Native Method)
  java.lang.Thread.sleep(Thread.java:442)
  java.lang.Thread.sleep(Thread.java:358)
  java.lang.Daemons$FinalizerWatchdogDaemon.sleepForNanos(Daemons.java:391)
  java.lang.Daemons$FinalizerWatchdogDaemon.waitForFinalization(Daemons.java:420)
  java.lang.Daemons$FinalizerWatchdogDaemon.runInternal(Daemons.java:326)
  java.lang.Daemons$Daemon.run(Daemons.java:140)
  java.lang.Thread.run(Thread.java:923)

Thread[HeapTaskDaemon,5,system]

Thread[FinalizerDaemon,5,system]
  java.lang.Object.wait(Native Method)
  java.lang.Object.wait(Object.java:442)
  java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:190)
  java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:211)
  java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:274)
  java.lang.Daemons$Daemon.run(Daemons.java:140)
  java.lang.Thread.run(Thread.java:923)

Thread[Jit thread pool worker thread 0,5,system]

Thread[Signal Catcher,10,system]

Thread[grpc-okhttp-0,5,main]
  libcore.io.Linux.poll(Native Method)
  libcore.io.ForwardingOs.poll(ForwardingOs.java:168)
  libcore.io.BlockGuardOs.poll(BlockGuardOs.java:263)
  libcore.io.ForwardingOs.poll(ForwardingOs.java:168)
  android.system.Os.poll(Os.java:430)
  libcore.io.IoBridge.poll(IoBridge.java:676)
  java.net.PlainSocketImpl.socketAccept(PlainSocketImpl.java:194)
  java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:451)
  java.net.ServerSocket.implAccept(ServerSocket.java:547)
  java.net.ServerSocket.accept(ServerSocket.java:515)
  io.grpc.okhttp.OkHttpServer.acceptConnections(OkHttpServer.java:100)
  io.grpc.okhttp.OkHttpServer.$r8$lambda$nWZgluu-gd0CBu46dJMXNIRQajA(Unknown Source:0)
  io.grpc.okhttp.OkHttpServer$$ExternalSyntheticLambda0.run(Unknown Source:2)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
  java.lang.Thread.run(Thread.java:923)
                     
Thread[DefaultDispatcher-worker-1,5,main]
2023-03-27 10:27:25.878  9084-9112  THREAD_STATE            com.example.camera_app               E      java.lang.Object.wait(Native Method)
  java.lang.Object.wait(Object.java:442)
  java.lang.Object.wait(Object.java:568)
  io.grpc.internal.ServerImpl.awaitTermination(ServerImpl.java:320)
  pl.leancode.patrol.PatrolServer.blockUntilShutdown(PatrolServer.kt:39)
  pl.leancode.patrol.PatrolTestRule$launchActivity$1.invokeSuspend(PatrolTestRule.kt:25)
  kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
  kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
  kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
  kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
  kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
  kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

Thread[ReferenceQueueDaemon,5,system]
  java.lang.Object.wait(Native Method)
  java.lang.Object.wait(Object.java:442)
  java.lang.Object.wait(Object.java:568)
  java.lang.Daemons$ReferenceQueueDaemon.runInternal(Daemons.java:218)
  java.lang.Daemons$Daemon.run(Daemons.java:140)
  java.lang.Thread.run(Thread.java:923)

Thread[main,5,main]
  android.os.MessageQueue.nativePollOnce(Native Method)
  android.os.MessageQueue.next(MessageQueue.java:335)
  android.os.Looper.loop(Looper.java:193)
  android.app.ActivityThread.main(ActivityThread.java:7876)
  java.lang.reflect.Method.invoke(Native Method)
  com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

Thread[Binder:9084_2,5,main]

Thread[Binder:9084_1,5,main]

Thread[InstrumentationConnectionThread,5,main]
  android.os.MessageQueue.nativePollOnce(Native Method)
  android.os.MessageQueue.next(MessageQueue.java:335)
  android.os.Looper.loop(Looper.java:193)
  android.os.HandlerThread.run(HandlerThread.java:67)

Thread[DefaultDispatcher-worker-2,5,main]
  sun.misc.Unsafe.park(Native Method)
  java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:353)
  kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.park(CoroutineScheduler.kt:795)
  kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.tryPark(CoroutineScheduler.kt:740)
  kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:711)
  kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

Thread[MonitoringInstrumentation,5,main]
  java.lang.Object.wait(Native Method)
  java.lang.Object.wait(Object.java:442)
  java.lang.Object.wait(Object.java:568)
  android.app.Instrumentation.startActivitySync(Instrumentation.java:528)
  android.app.Instrumentation.startActivitySync(Instrumentation.java:465)
  androidx.test.runner.MonitoringInstrumentation.access$001(MonitoringInstrumentation.java:102)
  androidx.test.runner.MonitoringInstrumentation$4.call(MonitoringInstrumentation.java:540)
  androidx.test.runner.MonitoringInstrumentation$4.call(MonitoringInstrumentation.java:537)
  java.util.concurrent.FutureTask.run(FutureTask.java:266)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
  java.lang.Thread.run(Thread.java:923)
```
</details>

Note that the error only appeared in the logcat (no error from the CLI which makes it seem to hang forever)


The `develop` command gave a similar result but the CLI (with --verbose) mentionned this:
```
        V/FlutterTestRunner(12075): launchActivity failed, possibly because the activity was already running. java.lang.RuntimeException: Could not launch intent Intent { act=android.intent.action.MAIN flg=0x14000000 cmp=com.example.camera_app/.MainActivity } within 45000 milliseconds. Perhaps the main thread has not gone idle within a reasonable amount of time? There could be an animation or something constantly repainting the screen. Or the activity is doing network calls on creation? See the threaddump logs. For your reference the last time the event queue was idle before your activity launch request was 1679906315630 and now the last time the queue went idle was: 1679906315630. If these numbers are the same your activity might be hogging the event queue.
        V/FlutterTestRunner(12075): Try disabling auto-launch of the activity, e.g. ActivityTestRule<>(MainActivity.class, true, false);
```

I found similar logs in the logcat:

<details>
<summary>Logs</summary>

```
 2023-03-27 10:39:20.822 12075-12102 THREAD_STATE            com.example.camera_app               E    Thread[Binder:12075_3,5,main]

  Thread[Profile Saver,5,system]

  Thread[Instr: androidx.test.runner.AndroidJUnitRunner,5,main]
    dalvik.system.VMStack.getThreadStackTrace(Native Method)
    java.lang.Thread.getStackTrace(Thread.java:1736)
    java.lang.Thread.getAllStackTraces(Thread.java:1812)
    androidx.test.runner.MonitoringInstrumentation.getThreadState(MonitoringInstrumentation.java:748)
    androidx.test.runner.MonitoringInstrumentation.dumpThreadStateToOutputs(MonitoringInstrumentation.java:743)
    androidx.test.runner.MonitoringInstrumentation.startActivitySync(MonitoringInstrumentation.java:547)
    androidx.test.rule.ActivityTestRule.launchActivity(ActivityTestRule.java:376)
    pl.leancode.patrol.PatrolTestRule.launchActivity(PatrolTestRule.kt:28)
    dev.flutter.plugins.integration_test.FlutterTestRunner.run(FlutterTestRunner.java:61)
    org.junit.runners.Suite.runChild(Suite.java:128)
    org.junit.runners.Suite.runChild(Suite.java:27)
    org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
    org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
    org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
    org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
    org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
    org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
    org.junit.runners.ParentRunner.run(ParentRunner.java:413)
    org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    org.junit.runner.JUnitCore.run(JUnitCore.java:115)
    androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:67)
    androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:58)
    androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:446)
    android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2213)

  Thread[FinalizerDaemon,5,system]
    java.lang.Object.wait(Native Method)
    java.lang.Object.wait(Object.java:442)
    java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:190)
    java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:211)
    java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:274)
    java.lang.Daemons$Daemon.run(Daemons.java:140)
    java.lang.Thread.run(Thread.java:923)

  Thread[HeapTaskDaemon,5,system]

  Thread[ReferenceQueueDaemon,5,system]
    java.lang.Object.wait(Native Method)
    java.lang.Object.wait(Object.java:442)
    java.lang.Object.wait(Object.java:568)
    java.lang.Daemons$ReferenceQueueDaemon.runInternal(Daemons.java:218)
    java.lang.Daemons$Daemon.run(Daemons.java:140)
    java.lang.Thread.run(Thread.java:923)

  Thread[FinalizerWatchdogDaemon,5,system]
    java.lang.Thread.sleep(Native Method)
    java.lang.Thread.sleep(Thread.java:442)
    java.lang.Thread.sleep(Thread.java:358)
    java.lang.Daemons$FinalizerWatchdogDaemon.sleepForNanos(Daemons.java:391)
    java.lang.Daemons$FinalizerWatchdogDaemon.waitForFinalization(Daemons.java:420)
    java.lang.Daemons$FinalizerWatchdogDaemon.runInternal(Daemons.java:326)
    java.lang.Daemons$Daemon.run(Daemons.java:140)
    java.lang.Thread.run(Thread.java:923)

  Thread[Signal Catcher,10,system]

  Thread[grpc-okhttp-0,5,main]
    libcore.io.Linux.poll(Native Method)
    libcore.io.ForwardingOs.poll(ForwardingOs.java:168)
    libcore.io.BlockGuardOs.poll(BlockGuardOs.java:263)
    libcore.io.ForwardingOs.poll(ForwardingOs.java:168)
    android.system.Os.poll(Os.java:430)
    libcore.io.IoBridge.poll(IoBridge.java:676)
    java.net.PlainSocketImpl.socketAccept(PlainSocketImpl.java:194)
    java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:451)
    java.net.ServerSocket.implAccept(ServerSocket.java:547)
    java.net.ServerSocket.accept(ServerSocket.java:515)
    io.grpc.okhttp.OkHttpServer.acceptConnections(OkHttpServer.java:100)
    io.grpc.okhttp.OkHttpServer.$r8$lambda$nWZgluu-gd0CBu46dJMXNIRQajA(Unknown Source:0)
  2023-03-27 10:39:20.822 12075-12102 THREAD_STATE            com.example.camera_app               E      io.grpc.okhttp.OkHttpServer$$ExternalSyntheticLambda0.run(Unknown Source:2)
      java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
      java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
      java.lang.Thread.run(Thread.java:923)

    Thread[DefaultDispatcher-worker-1,5,main]
      sun.misc.Unsafe.park(Native Method)
      java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:353)
      kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.park(CoroutineScheduler.kt:795)
      kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.tryPark(CoroutineScheduler.kt:740)
      kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:711)
      kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

    Thread[Jit thread pool worker thread 0,5,system]

    Thread[main,5,main]
      android.os.MessageQueue.nativePollOnce(Native Method)
      android.os.MessageQueue.next(MessageQueue.java:335)
      android.os.Looper.loop(Looper.java:193)
      android.app.ActivityThread.main(ActivityThread.java:7876)
      java.lang.reflect.Method.invoke(Native Method)
      com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
      com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

    Thread[Binder:12075_2,5,main]

    Thread[Binder:12075_1,5,main]

    Thread[InstrumentationConnectionThread,5,main]
      android.os.MessageQueue.nativePollOnce(Native Method)
      android.os.MessageQueue.next(MessageQueue.java:335)
      android.os.Looper.loop(Looper.java:193)
      android.os.HandlerThread.run(HandlerThread.java:67)

    Thread[DefaultDispatcher-worker-2,5,main]
      java.lang.Object.wait(Native Method)
      java.lang.Object.wait(Object.java:442)
      java.lang.Object.wait(Object.java:568)
      io.grpc.internal.ServerImpl.awaitTermination(ServerImpl.java:320)
      pl.leancode.patrol.PatrolServer.blockUntilShutdown(PatrolServer.kt:39)
      pl.leancode.patrol.PatrolTestRule$launchActivity$1.invokeSuspend(PatrolTestRule.kt:25)
      kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
      kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
      kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
      kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
      kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
      kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

    Thread[MonitoringInstrumentation,5,main]
      java.lang.Object.wait(Native Method)
      java.lang.Object.wait(Object.java:442)
      java.lang.Object.wait(Object.java:568)
      android.app.Instrumentation.startActivitySync(Instrumentation.java:528)
      android.app.Instrumentation.startActivitySync(Instrumentation.java:465)
      androidx.test.runner.MonitoringInstrumentation.access$001(MonitoringInstrumentation.java:102)
      androidx.test.runner.MonitoringInstrumentation$4.call(MonitoringInstrumentation.java:540)
      androidx.test.runner.MonitoringInstrumentation$4.call(MonitoringInstrumentation.java:537)
      java.util.concurrent.FutureTask.run(FutureTask.java:266)
      java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
      java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
      java.lang.Thread.run(Thread.java:923)
```
</details>

**Comment by apalala-dev** [comment]
@bartekpacia Any idea on how we could fix this?

**Comment by bartekpacia** [comment]
Hm, strange. But I'm glad to hear that it at least started to work on another branch.

> Thanks for the help!

Yeah, happy to help and thanks for the awesome plugin :) Unfortunately, my time is limited so I can't help you as much as I'd wish, but feel free to ask me in case of any problems/questions.

**Comment by apalala-dev** [comment]
I made an other PR (#307) which fixes some of the tests that didn't pass and include your changes. I'm closing this PR since the changes are also there.

There are still some behaviours a bit weird on my device: once the apps for testing are installed, I need to launch manually my app to be able to run the tests on it. It may be related to this specific device.
On emulator it works fine, and same for Firebase Test Lab!

Thanks again for the help 🙏

**Pull request closed without merging**
