### PR TITLE
🐛 inverted preview fix

### PR DESCRIPTION
**Pull request by g-apparence**
## Description
- tablet devices inverts preview 

So we have to rotate the preview and change the scale ratio according to this to.

### CODE REVIEW

**Comment by g-apparence** [comment]
If that's streched I think that this is because the preview size is wrong on your tablet.
Could you tell me which device you used?

**Comment by InspectlyMads** [comment]
> If that's streched I think that this is because the preview size is wrong on your tablet. Could you tell me which device you used?

Ios:
- Tested on physical iPad 9. generation with the pr changes
I have observed that rotations is still wrong. 
- Landscape-left is now upside 
- Landscape-right is correct. 
- Portait-up is now sideways where as portrait was correct before the pullrequest. 
- Portrait-down is upside down
 
Android: 
- Tested on emulated android tablet with the pr changes
I can no longer reproduce the issue on my android emulator tablet. The orientation now seem to behave like on phones.

Furthermore I have added a review explaining the issues at hand and a proposal for a solution

**Comment by InspectlyMads** [comment]
@g-apparence Do you need anything else from me here? :)

**Comment by g-apparence** [comment]
I have to test this on all my phones then I'll merge it. 
Sorry I'm currently releasing an app so I don't have that much time. (it also uses CamerAwesome)

**Pull request closed without merging**
